version: 0.0
os: linux
files:
   - source: /restservice/target
     destination: /var/lib/tomcat8/webapps
hooks:
   BeforeInstall:
      - location: scripts/app-stop.sh
        timeout: 10
   ApplicationStart:
      - location: scripts/app-start.sh
        timeout: 60
   ValidateService:
      - location: scripts/app-verification.sh
        timeout: 300
